# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6099d9cc5e84d807a5f57e63cb9abcaee37ea77870313ead03281d3c3a893215bccd32a67a10dd5f374e1b06b1b7cd66fdf56c9afc6042ee46ea37d0a6c916e4

test:
  secret_key_base: 2dc503d5264cb23752be252762227952a57155e727dcbf69eacd9b708de7ded14aedd33089d77b3dd6e286054b4ba3cb09d5b81cbb99112906865f0cb5ca43ef

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
